import { fileURLToPath } from 'node:url';
import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(ts|tsx)'],

  // Controls, viewport, actions, interactions and backgrounds all ship in
  // Storybook core as of v9 - only docs (autogenerated component docs) and
  // a11y (accessibility checks) need to be added explicitly.
  addons: ['@storybook/addon-docs', '@storybook/addon-a11y'],

  framework: {
    name: '@storybook/react-vite',
    options: {},
  },

  typescript: {
    // The full TS-based docgen is slower; react-docgen is fast enough and
    // good enough for the simple prop shapes used by these components.
    reactDocgen: 'react-docgen',
  },

  // The app resolves `@/*` to `src/*` (see vite.config.ts / tsconfig.app.json).
  // Storybook's Vite builder doesn't read the app's vite.config.ts on its
  // own, so the same alias is set up here.
  async viteFinal(viteConfig) {
    const { mergeConfig } = await import('vite');

    return mergeConfig(viteConfig, {
      resolve: {
        alias: {
          '@': fileURLToPath(new URL('../src', import.meta.url)),
        },
      },
    });
  },
};

export default config;
